### ISSUE TITLE
Fail to start kinto server

### ISSUE THREAD

**Issue by windwww** [Kinto/kinto#1014]
I installed kinto server to linux 16.04. I follow the step on http://kinto.readthedocs.io/en/latest/tutorials/install.html#linux to install kinto server. I use "apt-get install gcc" as well. After I install, I get the following error.

root@kinto:~# http http://db.i-learn.com.hk:8888/v1/ --auth "token:my-secret"   HTTP/1.1 500 Internal Server Error
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 183
Content-Type: application/json
Date: Thu, 05 Jan 2017 07:48:10 GMT
Server: waitress
X-Content-Type-Options: nosniff

{
    "code": 500,
    "errno": 999,
    "error": "Internal Server Error",
    "info": "https://github.com/Kinto/kinto/issues/",
    "message": "A programmatic error occured, developers have been informed."
}

The log is shown below:
(env) root@kinto:~# kinto start
/root/env/local/lib/python2.7/site-packages/kinto/core/initialization.py:568: UserWarning: HTTPS is not enabled
  warnings.warn('HTTPS is not enabled')
2017-01-05 07:47:49,137 INFO  [kinto.core][MainThread] Running kinto 5.1.0.
Starting server in PID 8749.
Serving on http://0.0.0.0:8888
2017-01-05 07:48:10,407 ERROR [kinto.core.views.errors][waitress] "GET   /v1/" ? (? ms) 'BasicAuthAuthenticationPolicy' object has no attribute '_get_credentials' agent=HTTPie/0.9.2 authn_type=None errno=None exception=Traceback (most recent call last):
  File "/root/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
    reraise(*exc_info)
  File "/root/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
    response = handler(request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/root/env/local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/root/env/local/lib/python2.7/site-packages/cornice/service.py", line 493, in wrapper
    response = view_(request)
  File "/root/env/local/lib/python2.7/site-packages/kinto/core/views/hello.py", line 33, in get_hello
    if Authenticated in request.effective_principals:
  File "/root/env/local/lib/python2.7/site-packages/pyramid/security.py", line 375, in effective_principals
    return policy.effective_principals(self)
  File "/root/env/local/lib/python2.7/site-packages/pyramid_multiauth/__init__.py", line 119, in effective_principals
    userid = policy.authenticated_userid(request)
  File "/root/env/local/lib/python2.7/site-packages/pyramid/authentication.py", line 71, in authenticated_userid
    userid = self.unauthenticated_userid(request)
  File "/root/env/local/lib/python2.7/site-packages/kinto/core/authentication.py", line 29, in unauthenticated_userid
    credentials = self._get_credentials(request)
AttributeError: 'BasicAuthAuthenticationPolicy' object has no attribute '_get_credentials' lang=None uid=None
2017-01-05 07:48:10,412 INFO  [kinto.core.initialization][waitress] "GET   /v1/" 500 (11 ms) request.summary agent=HTTPie/0.9.2 authn_type=None errno=999 lang=None time=2017-01-05T07:48:10 uid=None

**Comment by windwww** [comment]
I guess it is related to #1008 too.

**Comment by windwww** [comment]
I just down the version of pyramid with:
pip install "pyramid==1.7.3"

it solved.
