### ISSUE TITLE
Crash with DELETE .../records?_limit=1

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1019]
```
"DELETE /v1/buckets/staging/collections/addons/records?_limit=1" ? (? ms) list index out of range agent=HTTPie/0.9.2 authn_type=basicauth collection_id=record collection_timestamp=1484323214484 errno=None exception=Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
    reraise(*exc_info)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
    response = handler(request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/cornice/service.py", line 491, in wrapper
    response = view_()
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/kinto/core/resource/__init__.py", line 390, in collection_delete
    return self.postprocess(deleted, action=action, old=records)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/kinto/core/resource/__init__.py", line 1254, in postprocess
    data = super(ShareableResource, self).postprocess(result, action, old)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/kinto/core/resource/__init__.py", line 725, in postprocess
    old=old)
  File "/home/mathieu/Code/Mozilla/kinto-dist/.venv/local/lib/python2.7/site-packages/kinto/core/events.py", line 147, in notify_resource_event
    impacted.append({'new': new, 'old': old[i]})
IndexError: list index out of range lang=None uid=cbd3731f18c97ebe1d31d9846b5f1b95cf8eeeae586e201277263434041e99d1

**Comment by leplatrem** [comment]
Cannot reproduce :/
