### ISSUE TITLE
Accounts post API crashes with unset id (if basicauth is enabled too)

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#1177]
```
gsurita-30820:~ gsurita$ echo '{"data": {"password": "me"}}' | http post localhost:8888/v1/accounts -a foo:bar
HTTP/1.1 500 Internal Server Error
(...)
```

```
Traceback (most recent call last):
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
    reraise(*exc_info)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
    response = handler(request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 300, in secured_view
    return view(context, request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/Users/gsurita/kinto/kinto/.venv/lib/python3.6/site-packages/cornice/service.py", line 491, in wrapper
    response = view_()
  File "/Users/gsurita/kinto/kinto/kinto/plugins/accounts/views.py", line 81, in collection_post
    result = super(Account, self).collection_post()
  File "/Users/gsurita/kinto/kinto/kinto/core/resource/__init__.py", line 341, in collection_post
    new_record = self.process_record(new_record)
  File "/Users/gsurita/kinto/kinto/kinto/plugins/accounts/views.py", line 102, in process_record
    if new[self.model.id_field] != self.request.selected_userid:
KeyError: 'id'
```

**Comment by gabisurita** [comment]
Just realized basicauth was also enabled. We should maybe clarify in the documentation that's not possible to use both at the same time.

**Comment by leplatrem** [comment]
In theory we should be able to use both (I mean for consistency). I suggest that we keep this open and investigate what we can do (fix bug, document limitation, raise configurationerror ... )

**Comment by gabisurita** [comment]
> In theory we should be able to use both (I mean for consistency).

How would that work? Check if an account exist and use it otherwise generate a basicauth principal? I don't know, this sounds a bit confusing. 

Now that we are here, it's probably a good idea to test (and support) integration with portier and other authentication plugins.

**Comment by leplatrem** [comment]
> How would that work? Check if an account exist and use it otherwise generate a basicauth principal?

We rely on Pyramid Multiauth. It iterates on every auth methods until one is successful.

I agree this can be very confusing. For example in prod, we once had ldap+basicauth and when users entered wrong ldap credentials they would end up authenticated as `basicauth:*` instead of receiving 401.
