### ISSUE TITLE
Hunting race conditions

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1290]
Here is a script called `race.py`.

```python
import aiohttp
import asyncio
import async_timeout
import base64

AUTH = 'Basic ' + base64.b64encode(b'test:test').decode('utf-8')
URL = 'http://localhost:8888/v1/buckets/default/collections/plop'


async def create_collection(session):
    async with session.put(URL, data='{"data": {"id": "plop"}}', headers={"Content-Type": "application/json"}) as response:
        text = await response.text()
        print(text)


async def set_data(session):
    with async_timeout.timeout(10):
        async with session.put(URL, data='{"data": {"a": 1}}', headers=[("Content-Type", "application/json")]) as response:
            text = await response.text()
            print(text)
            if response.status == 409:
                print(response.headers)


async def set_permission(session):
    with async_timeout.timeout(10):
        async with session.put(URL, data='{"permissions": {"read": ["github:n1k0"]}}', headers=[("Content-Type", "application/json")]) as response:
            text = await response.text()
            print(text)
            if response.status == 409:
                print(response.headers)


async def fetch(session):
    with async_timeout.timeout(10):
        async with session.get(URL) as response:
            resp = await response.json()
            print(resp)
            assert resp['data'].get('a') == 1


async def remove_bucket(session):
    async with session.delete('http://localhost:8888/v1/buckets/default') as response:
        text = await response.text()
        print(text)
        if response.status == 409:
            print(response.headers)

async def remove_permission(session):
    async with session.patch(URL, data='[ { "op": "remove", "path": "/permissions/read/github:n1k0" } ]', headers={'Content-Type': 'application/json-patch+json'}) as response:
        return await response.json()


async def main():
    async with aiohttp.ClientSession(headers={"Authorization": AUTH}) as session1:
        await remove_bucket(session1)
        await create_collection(session1)
        await asyncio.gather(set_permission(session1), set_data(session1))
        await fetch(session1)

        resp1 = await remove_permission(session1)
        print(resp1)
        assert resp1['data'].get('a') == 1
        assert 'read' not in resp1['permissions']

        await fetch(session1)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

It tries to make two requests "simultaneously", one which sets a collection's data, and another which adds a permission. Then it checks to see that the data is correct.

Run kinto using the tests/kinto.ini config from kinto-http.js. Then, run the above script using a command like (fish shell syntax):

```
set x 0; while python race.py ; set x (math $x + 1); date; echo $x; end
```

On my machine, the script eventually fails (although sometimes it takes more time -- up to 2k iterations). Either the `set_data` or the `set_permission` call gets a 409 integrity error.

```
{"message":"Integrity constraint violated, please retry.","code":409,"errno":122,"error":"Conflict"}
{"data":{"a":1,"id":"plop","last_modified":1498756145457},"permissions":{"write":["basicauth:c5f27b9d5865fee5a3df09402958c11146286ec9c0599207d3ca4c2715a28056"]}}
{'data': {'a': 1, 'last_modified': 1498756145457, 'id': 'plop'}, 'permissions': {'write': ['basicauth:c5f27b9d5865fee5a3df09402958c11146286ec9c0599207d3ca4c2715a28056']}}
{'errno': 107, 'error': 'Invalid parameters', 'code': 400, 'message': "body: JSON Patch operation failed: can't remove non-existent object 'github:n1k0'", 'details': [{'location': 'body', 'description': "JSON Patch operation failed: can't remove non-existent object 'github:n1k0'", 'name': None}]}
Traceback (most recent call last):
  File "race-trash.py", line 59, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "race-trash.py", line 52, in main
    assert resp1['data'].get('a') == 1
KeyError: 'data'
```

```
{"data":{"id":"plop","last_modified":1498756212749},"permissions":{"read":["github:n1k0"],"write":["basicauth:c5f27b9d5865fee5a3df09402958c11146286ec9c0599207d3ca4c2715a28056"]}}
{"message":"Integrity constraint violated, please retry.","code":409,"errno":122,"error":"Conflict"}
{'data': {'id': 'plop', 'last_modified': 1498756212749}, 'permissions': {'read': ['github:n1k0'], 'write': ['basicauth:c5f27b9d5865fee5a3df09402958c11146286ec9c0599207d3ca4c2715a28056']}}
Traceback (most recent call last):
  File "race-trash.py", line 59, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "race-trash.py", line 48, in main
    await fetch(session1)
  File "race-trash.py", line 29, in fetch
    assert resp['data'].get('a') == 1
AssertionError
```

I believe these correspond to the intermittent failures we've seen on kinto-http.js tests.

I was surprised for these to get 409 integrity errors because the memory backend is not transactional. However, what happens is in `UserResource`; a `put` fetches the record to apply 412 "If-Match"/"If-None-Match" checks, and then uses that fetched record to either `create` or `update`. If two requests happen at the same time, they can both try to do a `create`; one will "win", and the other will discover that the record already exists, so raise an `IntegrityError`.

1. Is this OK? Should a client be able to expect not to get an IntegrityError in these kinds of circumstances? We are correctly reporting an IntegrityError with a Retry-After, so arguably this is all working as designed.
2. However, if the record already exists (by uncommenting the line marked "see (2)"), it's possible for the two "updates" to race with the loser not getting saved. Is this OK? The memory backend doesn't have any kind of transactional guarantees and it's essentially only for testing.

**Comment by glasserc** [comment]
I believe point 2 (above) may also apply to the Postgres backend.

**Comment by Natim** [comment]
I like the fact that you encountered a 409, it seems to be a good behavior to me.

**Comment by leplatrem** [comment]
In Cache, `get()` that deletes and reads in two differnt intruscutions

https://github.com/Kinto/kinto/blob/7.3.1/kinto/core/cache/postgresql/__init__.py#L142-L150

**Comment by leplatrem** [comment]
@glasserc can we close this?

**Comment by glasserc** [comment]
Let's close it in favor of #1407..
