### ISSUE TITLE
Another race condition: records_pkey

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1388]
This program races puts with the delete_bucket and eventually generates the records_pkey error:

```
"""
Another race-trash script that tries to race delete-bucket with checking for some records
"""
import aiohttp
import asyncio
import async_timeout
import base64
import psycopg2

AUTH = 'Basic ' + base64.b64encode(b'test:test').decode('utf-8')
BUCKET = 'http://localhost:8888/v1/buckets/default'
COLLECTION = BUCKET + '/collections/storage-sync-crypto'
RECORDS_URL = COLLECTION + '/records?_since=0'
A_CERTAIN_RECORD = COLLECTION + '/records/keys'

async def get_new_records(session):
    await asyncio.sleep(.017)
    with async_timeout.timeout(10):
        async with session.get(RECORDS_URL) as response:
            resp = await response.json()
            print(resp)
            assert response.status == 200 or response.status == 403


async def put_record(session):
    with async_timeout.timeout(10):
        async with session.put(A_CERTAIN_RECORD, data='{"data": {"a": 1}}', headers=[("Content-Type", "application/json")]) as response:
            resp = await response.json()
            print(resp)
            assert response.status < 300


async def delete_bucket(session):
    async with session.delete(BUCKET) as response:
        text = await response.text()
        print(text)
        assert response.status == 200


def check_both_deleted_and_records(conn):
    cur = conn.cursor()
    cur.execute("SELECT * FROM records r JOIN deleted d ON (r.id = d.id AND r.parent_id = d.parent_id AND r.collection_id = d.collection_id);")
    assert not cur.fetchone()
    cur.close()


async def main():
    conn = psycopg2.connect("dbname=postgres user=postgres password=postgres host=localhost")
    async with aiohttp.ClientSession(headers={"Authorization": AUTH}) as session1:
        #await put_record(session1)
        things = [
            delete_bucket(session1),
            put_record(session1),
        ]
        await asyncio.gather(*things)
        check_both_deleted_and_records(conn)
    conn.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Stdout:

```
{'permissions': {'write': ['basicauth:44ac0e1157457b4ff75a88b490cd735f73a27d5c8ac5b3fb4672d449969d88ea']}, 'data': {'a': 1, 'id': 'keys', 'last_modified': 1511370407001}}
{"code":409,"errno":122,"error":"Conflict","message":"Integrity constraint violated, please retry."}
Traceback (most recent call last):
  File "../race-trash-2.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "../race-trash-2.py", line 55, in main
    await asyncio.gather(*things)
  File "../race-trash-2.py", line 37, in delete_bucket
    assert response.status == 200
AssertionError
```

Logs:

```
2017-11-22 12:06:47,018 ERROR [kinto.core.storage.postgresql.client][waitress] (psycopg2.IntegrityError) duplicate key value violates unique constraint "records_pkey"
DETAIL:  Key (id, parent_id, collection_id)=(3f2e55d2-25ad-5fa9-3dcb-c0f29235627f, , bucket) already exists.
 [SQL: '\n        WITH delete_potential_tombstone AS (\n            DELETE FROM deleted\n             WHERE id = %(object_id)s\n               AND parent_id = %(parent_id)s\n               AND collection_id = %(collection_id)s\n        )\n        INSERT INTO records (id, parent_id, collection_id, data, last_modified)\n        VALUES (%(object_id)s, %(parent_id)s,\n                %(collection_id)s, (%(data)s)::JSONB,\n                from_epoch(%(last_modified)s))\n        \n        RETURNING id, as_epoch(last_modified) AS last_modified;\n        '] [parameters: {'object_id': '3f2e55d2-25ad-5fa9-3dcb-c0f29235627f', 'parent_id': '', 'collection_id': 'bucket', 'data': '{}', 'last_modified': None}]
Traceback (most recent call last):
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "records_pkey"
DETAIL:  Key (id, parent_id, collection_id)=(3f2e55d2-25ad-5fa9-3dcb-c0f29235627f, , bucket) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ethan/Jobs/Mozilla/kinto/kinto/core/storage/postgresql/client.py", line 35, in connect
    yield session
  File "/home/ethan/Jobs/Mozilla/kinto/kinto/core/storage/postgresql/__init__.py", line 318, in create
    result = conn.execute(query % safe_holders, placeholders)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1154, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/ethan/Jobs/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "records_pkey"
DETAIL:  Key (id, parent_id, collection_id)=(3f2e55d2-25ad-5fa9-3dcb-c0f29235627f, , bucket) already exists.
 [SQL: '\n        WITH delete_potential_tombstone AS (\n            DELETE FROM deleted\n             WHERE id = %(object_id)s\n               AND parent_id = %(parent_id)s\n               AND collection_id = %(collection_id)s\n        )\n        INSERT INTO records (id, parent_id, collection_id, data, last_modified)\n        VALUES (%(object_id)s, %(parent_id)s,\n                %(collection_id)s, (%(data)s)::JSONB,\n                from_epoch(%(last_modified)s))\n        \n        RETURNING id, as_epoch(last_modified) AS last_modified;\n        '] [parameters: {'object_id': '3f2e55d2-25ad-5fa9-3dcb-c0f29235627f', 'parent_id': '', 'collection_id': 'bucket', 'data': '{}', 'last_modified': None}]
2017-11-22 12:06:47,022 INFO  [request.summary][waitress] 
```

**Comment by glasserc** [comment]
I've also gotten deadlocks from this script. In that case, try uncommenting the put_record call and changing it to delete_bucket.

I've also had this script "succeed" from Kinto responses but leave records in both deleted and records.

**Comment by glasserc** [comment]
I'm extracting the "both deleted and records" bug as #1396.

I believe what's happening in this one is something like the following:

- The record in question (the default bucket) is deleted at the top of the request.
- Request 1 and request 2 both start around the same time.
- Both requests do `self.get()` to check if the request exists already. It doesn't.
- Both try to delete the tombstone and insert into `records`. One succeeds, the other gets an integrity error.

I don't believe #1386 will fix this one -- we need to stop doing explicit checks for the record using `self.get()`, because that's a classic TOCTOU error.

**Comment by glasserc** [comment]
This is also a duplicate of #1376. I need to refer to existing bugs more often.
