### ISSUE TITLE
Installing 1.4.0 through pip and starting the server triggers an error

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#205]
This only happens when installing the 1.4.0 version, not the latest 1.5.0:

```
$ .venv/bin/pip install kinto==1.4.0 --upgrade
Downloading/unpacking kinto==1.4.0
  Downloading kinto-1.4.0-py2.py3-none-any.whl
Requirement already up-to-date: jsonschema==2.5.1 in ./.venv/lib/python2.7/site-packages (from kinto==1.4.0)
Requirement already up-to-date: waitress==0.8.10 in ./.venv/lib/python2.7/site-packages (from kinto==1.4.0)
Requirement already up-to-date: cliquet>=2.6.2,<=2.7 in ./.venv/lib/python2.7/site-packages (from kinto==1.4.0)
Installing collected packages: kinto
  Found existing installation: kinto 1.5.0
    Uninstalling kinto:
      Successfully uninstalled kinto
Successfully installed kinto
Cleaning up...
 niko@n1k0-moz ~/Sites/kinto.js (185-test-server-logging)
$ .venv/bin/pserve test/kinto.ini
2015-09-29 15:12:39,461 INFO  [venusian][MainThread] kinto.js test server 1.4.0 starting.
Traceback (most recent call last):
  File ".venv/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/kinto/__init__.py", line 49, in main
    config.scan("kinto.views", **kwargs)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 930, in scan
    ignore=ignore)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/Users/niko/Sites/kinto.js/.venv/lib/python2.7/site-packages/kinto/views/groups.py", line 6, in <module>
    from cliquet.authorization import get_object_id
ImportError: cannot import name get_object_id
```

**Comment by Natim** [comment]
The problem is that Kinto 1.4.0 should install Cliquet 2.6.x branch but the setup.py is wrong and it install the 2.7.0 instead.

    Successfully installed cliquet-2.7.0 kinto-1.4.0

We will try our best in the feature to correctly tag cliquet version numbers in kinto.
