### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#288]
On Master, python 3.4, running xml2kinto to add some data, on a redis storage

```bash
$ make serve
.venv/bin/kinto --ini config/kinto.ini migrate
.venv/bin/kinto --ini config/kinto.ini start
Starting subprocess with file monitor
2015-11-20 13:30:24,786 INFO  [venusian][MainThread] kinto 1.10.0.dev0 starting.
Starting server in PID 42452.
serving on http://0.0.0.0:8888
2015-11-20 13:30:28,263 ERROR [venusian][waitress] 'bytes' object has no attribute 'encode' exception=Traceback (most recent call last):
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 60, in tm_tween
    userid = unauthenticated_userid(request)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/pyramid/security.py", line 94, in unauthenticated_userid
    return request.unauthenticated_userid
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/pyramid/security.py", line 361, in unauthenticated_userid
    return policy.unauthenticated_userid(self)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/pyramid_multiauth/__init__.py", line 98, in unauthenticated_userid
    userid = policy.unauthenticated_userid(request)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/cliquet/authentication.py", line 31, in unauthenticated_userid
    userid = utils.hmac_digest(hmac_secret, credentials)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/cliquet/utils.py", line 135, in hmac_digest
    hashlib.sha256).hexdigest()
AttributeError: 'bytes' object has no attribute 'encode'
2015-11-20 13:30:28,264 INFO  [venusian][waitress] request.summary time=2015-11-20T13:30:28.263999; errno=999
```

**Comment by leplatrem** [comment]
`settings['userid_hmac_secret']` returns a value of `<class 'bytes'>` !
