### ISSUE TITLE
Wait until database starts before starting Kinto in Docker Compose

### ISSUE THREAD

**Issue by ZeroAurora** [Kinto/kinto#3008]
When starting kinto the first time using docker-compose, the startup failed and I could not access the API. The log tells me that kinto exited immediately after trying to connect the database, which hadn't been fully initialized then.

Maybe waiting for or retrying database connection can solve this problem.

See https://docs.docker.com/compose/startup-order/ for Docker's explanation.
<details>
<summary>Full log</summary>

```
kinto-db-1     | The files belonging to this database system will be owned by user "postgres".
kinto-db-1     | This user must also own the server process.
kinto-db-1     | 
kinto-db-1     | The database cluster will be initialized with locale "en_US.utf8".
kinto-db-1     | The default database encoding has accordingly been set to "UTF8".
kinto-db-1     | The default text search configuration will be set to "english".
kinto-db-1     | 
kinto-db-1     | Data page checksums are disabled.
kinto-db-1     | 
kinto-db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
kinto-db-1     | creating subdirectories ... ok
kinto-db-1     | selecting dynamic shared memory implementation ... posix
kinto-db-1     | selecting default max_connections ... 100
kinto-db-1     | selecting default shared_buffers ... 128MB
kinto-db-1     | selecting default time zone ... Etc/UTC
kinto-db-1     | creating configuration files ... ok
kinto-db-1     | running bootstrap script ... ok
kinto-db-1     | performing post-bootstrap initialization ... ok
kinto-web-1    | /app/kinto/core/initialization.py:563: UserWarning: HTTPS is not enabled
kinto-web-1    |   warnings.warn("HTTPS is not enabled")
kinto-web-1    | /app/kinto/core/storage/postgresql/client.py:98: UserWarning: Reuse existing PostgreSQL connection. Parameters permission_* will be ignored.
kinto-web-1    |   warnings.warn(msg)
kinto-web-1    | INFO   Running kinto 14.4.0.dev0.
kinto-web-1    | ERROR  (psycopg2.OperationalError) could not connect to server: Connection refused
kinto-web-1    |        Is the server running on host "db" (172.25.0.3) and accepting
kinto-web-1    |        TCP/IP connections on port 5432?
kinto-web-1    | 
kinto-web-1    | (Background on this error at: https://sqlalche.me/e/14/e3q8)
kinto-web-1    | Traceback (most recent call last):
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
kinto-web-1    |     return fn()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 307, in connect
kinto-web-1    |     return _ConnectionFairy._checkout(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
kinto-web-1    |     fairy = _ConnectionRecord.checkout(pool)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
kinto-web-1    |     rec = pool._do_get()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
kinto-web-1    |     self._dec_overflow()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
kinto-web-1    |     return self._create_connection()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
kinto-web-1    |     return _ConnectionRecord(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
kinto-web-1    |     self.__connect()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
kinto-web-1    |     pool.logger.debug("Error on connect(): %s", e)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
kinto-web-1    |     connection = pool._invoke_creator(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
kinto-web-1    |     return dialect.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
kinto-web-1    |     return self.dbapi.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
kinto-web-1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
kinto-web-1    | psycopg2.OperationalError: could not connect to server: Connection refused
kinto-web-1    |        Is the server running on host "db" (172.25.0.3) and accepting
kinto-web-1    |        TCP/IP connections on port 5432?
kinto-web-1    | 
kinto-web-1    | 
kinto-web-1    | The above exception was the direct cause of the following exception:
kinto-web-1    | 
kinto-web-1    | Traceback (most recent call last):
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/client.py", line 43, in connect
kinto-web-1    |     yield session
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 141, in get_installed_version
kinto-web-1    |     result = conn.execute(table_exists_query.format("objects"))
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
kinto-web-1    |     conn = self._connection_for_bind(bind)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
kinto-web-1    |     engine, execution_options
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
kinto-web-1    |     conn = bind.connect()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
kinto-web-1    |     return self._connection_cls(self, close_with_result=close_with_result)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
kinto-web-1    |     else engine.raw_connection()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
kinto-web-1    |     return self._wrap_pool_connect(self.pool.connect, _connection)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3216, in _wrap_pool_connect
kinto-web-1    |     e, dialect, self
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2070, in _handle_dbapi_exception_noconnection
kinto-web-1    |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
kinto-web-1    |     return fn()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 307, in connect
kinto-web-1    |     return _ConnectionFairy._checkout(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
kinto-web-1    |     fairy = _ConnectionRecord.checkout(pool)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
kinto-web-1    |     rec = pool._do_get()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
kinto-web-1    |     self._dec_overflow()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
kinto-web-1    |     return self._create_connection()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
kinto-web-1    |     return _ConnectionRecord(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
kinto-web-1    |     self.__connect()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
kinto-web-1    |     pool.logger.debug("Error on connect(): %s", e)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
kinto-web-1    |     connection = pool._invoke_creator(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
kinto-web-1    |     return dialect.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
kinto-web-1    |     return self.dbapi.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
kinto-web-1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
kinto-web-1    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
kinto-web-1    |        Is the server running on host "db" (172.25.0.3) and accepting
kinto-web-1    |        TCP/IP connections on port 5432?
kinto-web-1    | 
kinto-web-1    | (Background on this error at: https://sqlalche.me/e/14/e3q8)
kinto-web-1    | Traceback (most recent call last):
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
kinto-web-1    |     return fn()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 307, in connect
kinto-web-1    |     return _ConnectionFairy._checkout(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
kinto-web-1    |     fairy = _ConnectionRecord.checkout(pool)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
kinto-web-1    |     rec = pool._do_get()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
kinto-web-1    |     self._dec_overflow()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
kinto-web-1    |     return self._create_connection()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
kinto-web-1    |     return _ConnectionRecord(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
kinto-web-1    |     self.__connect()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
kinto-web-1    |     pool.logger.debug("Error on connect(): %s", e)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
kinto-web-1    |     connection = pool._invoke_creator(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
kinto-web-1    |     return dialect.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
kinto-web-1    |     return self.dbapi.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
kinto-web-1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
kinto-web-1    | psycopg2.OperationalError: could not connect to server: Connection refused
kinto-web-1    |        Is the server running on host "db" (172.25.0.3) and accepting
kinto-web-1    |        TCP/IP connections on port 5432?
kinto-web-1    | 
kinto-web-1    | 
kinto-web-1    | The above exception was the direct cause of the following exception:
kinto-web-1    | 
kinto-web-1    | Traceback (most recent call last):
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/client.py", line 43, in connect
kinto-web-1    |     yield session
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 141, in get_installed_version
kinto-web-1    |     result = conn.execute(table_exists_query.format("objects"))
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
kinto-web-1    |     conn = self._connection_for_bind(bind)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
kinto-web-1    |     engine, execution_options
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
kinto-web-1    |     conn = bind.connect()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
kinto-web-1    |     return self._connection_cls(self, close_with_result=close_with_result)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
kinto-web-1    |     else engine.raw_connection()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
kinto-web-1    |     return self._wrap_pool_connect(self.pool.connect, _connection)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3216, in _wrap_pool_connect
kinto-web-1    |     e, dialect, self
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2070, in _handle_dbapi_exception_noconnection
kinto-web-1    |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
kinto-web-1    |     return fn()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 307, in connect
kinto-web-1    |     return _ConnectionFairy._checkout(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
kinto-web-1    |     fairy = _ConnectionRecord.checkout(pool)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
kinto-web-1    |     rec = pool._do_get()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
kinto-web-1    |     self._dec_overflow()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
kinto-web-1    |     return self._create_connection()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
kinto-web-1    |     return _ConnectionRecord(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
kinto-web-1    |     self.__connect()
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
kinto-web-1    |     pool.logger.debug("Error on connect(): %s", e)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
kinto-web-1    |     with_traceback=exc_tb,
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
kinto-web-1    |     raise exception
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
kinto-web-1    |     connection = pool._invoke_creator(self)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
kinto-web-1    |     return dialect.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
kinto-web-1    |     return self.dbapi.connect(*cargs, **cparams)
kinto-web-1    |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
kinto-web-1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
kinto-web-1    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
kinto-web-1    |        Is the server running on host "db" (172.25.0.3) and accepting
kinto-web-1    |        TCP/IP connections on port 5432?
kinto-web-1    | 
kinto-web-1    | (Background on this error at: https://sqlalche.me/e/14/e3q8)
kinto-web-1    | 
kinto-web-1    | The above exception was the direct cause of the following exception:
kinto-web-1    | 
kinto-web-1    | Traceback (most recent call last):
kinto-web-1    |   File "/usr/local/bin/kinto", line 33, in <module>
kinto-web-1    |     sys.exit(load_entry_point('kinto', 'console_scripts', 'kinto')())
kinto-web-1    |   File "/app/kinto/__main__.py", line 217, in main
kinto-web-1    |     core_scripts.migrate(env, dry_run=dry_run)
kinto-web-1    |   File "/app/kinto/core/scripts.py", line 26, in migrate
kinto-web-1    |     getattr(registry, backend).initialize_schema(dry_run=dry_run)
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 97, in initialize_schema
kinto-web-1    |     return self.create_or_migrate_schema(dry_run)
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/migrator.py", line 44, in create_or_migrate_schema
kinto-web-1    |     version = self.get_installed_version()
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/__init__.py", line 178, in get_installed_version
kinto-web-1    |     return MAX_FLUSHABLE_SCHEMA_VERSION
kinto-web-1    |   File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
kinto-web-1    |     self.gen.throw(type, value, traceback)
kinto-web-1    |   File "/app/kinto/core/storage/postgresql/client.py", line 63, in connect
kinto-web-1    |     raise exceptions.BackendError(original=e) from e
kinto-web-1    | kinto.core.storage.exceptions.BackendError: OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
kinto-web-1    |        Is the server running on host "db" (172.25.0.3) and accepting
kinto-web-1    |        TCP/IP connections on port 5432?
kinto-web-1    | 
kinto-web-1    | (Background on this error at: https://sqlalche.me/e/14/e3q8)
kinto-web-1 exited with code 1
kinto-db-1     | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
kinto-db-1     | You can change this by editing pg_hba.conf or using the option -A, or
kinto-db-1     | --auth-local and --auth-host, the next time you run initdb.
kinto-db-1     | ok
kinto-db-1     | 
kinto-db-1     | 
kinto-db-1     | Success. You can now start the database server using:
kinto-db-1     | 
kinto-db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
kinto-db-1     | 
kinto-db-1     | waiting for server to start....2022-06-29 14:57:55.101 UTC [48] LOG:  starting PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
kinto-db-1     | 2022-06-29 14:57:55.108 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
kinto-db-1     | 2022-06-29 14:57:55.128 UTC [49] LOG:  database system was shut down at 2022-06-29 14:57:48 UTC
kinto-db-1     | 2022-06-29 14:57:55.137 UTC [48] LOG:  database system is ready to accept connections
kinto-db-1     |  done
kinto-db-1     | server started
kinto-db-1     | 
kinto-db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
kinto-db-1     | 
kinto-db-1     | waiting for server to shut down....2022-06-29 14:57:55.212 UTC [48] LOG:  received fast shutdown request
kinto-db-1     | 2022-06-29 14:57:55.219 UTC [48] LOG:  aborting any active transactions
kinto-db-1     | 2022-06-29 14:57:55.220 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
kinto-db-1     | 2022-06-29 14:57:55.220 UTC [50] LOG:  shutting down
kinto-db-1     | 2022-06-29 14:57:55.279 UTC [48] LOG:  database system is shut down
kinto-db-1     |  done
kinto-db-1     | server stopped
kinto-db-1     | 
kinto-db-1     | PostgreSQL init process complete; ready for start up.
kinto-db-1     | 
kinto-db-1     | 2022-06-29 14:57:55.335 UTC [1] LOG:  starting PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
kinto-db-1     | 2022-06-29 14:57:55.335 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
kinto-db-1     | 2022-06-29 14:57:55.335 UTC [1] LOG:  listening on IPv6 address "::", port 5432
kinto-db-1     | 2022-06-29 14:57:55.348 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
kinto-db-1     | 2022-06-29 14:57:55.361 UTC [60] LOG:  database system was shut down at 2022-06-29 14:57:55 UTC
kinto-db-1     | 2022-06-29 14:57:55.370 UTC [1] LOG:  database system is ready to accept connections
```
</details>

**Comment by yyzahran** [comment]
Hi, I'd like to work on this issue.

**Comment by Varun-Dhruv** [comment]
Hi,I'd like to work on this issue
