### ISSUE TITLE
docker-compose up  fails

### ISSUE THREAD

**Issue by hansent** [Kinto/kinto#325]
using the `docker-compose.yml` downloaded by  `wget https://raw.githubusercontent.com/Kinto/kinto/master/docker-compose.yml`

as described here: http://kinto.readthedocs.org/en/latest/tutorials/run-kinto.html#using-docker

output: 
```
$ docker-compose up
Starting kinto_db_1...
Starting kinto_web_1...
Attaching to kinto_db_1, kinto_web_1
db_1  | The files belonging to this database system will be owned by user "postgres".
db_1  | This user must also own the server process.
db_1  | 
db_1  | The database cluster will be initialized with locale "en_US.utf8".
db_1  | The default database encoding has accordingly been set to "UTF8".
db_1  | The default text search configuration will be set to "english".
db_1  | 
db_1  | Data page checksums are disabled.
db_1  | 
db_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1  | creating subdirectories ... ok
db_1  | selecting default max_connections ... 100
db_1  | selecting default shared_buffers ... 128MB
db_1  | selecting dynamic shared memory implementation ... posix
db_1  | creating configuration files ... ok
db_1  | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
db_1  | initializing pg_authid ... ok
db_1  | initializing dependencies ... ok
db_1  | creating system views ... ok
db_1  | loading system objects' descriptions ... ok
db_1  | creating collations ... ok
db_1  | creating conversions ... ok
db_1  | creating dictionaries ... ok
db_1  | setting privileges on built-in objects ... ok
db_1  | creating information schema ... ok
db_1  | loading PL/pgSQL server-side language ... ok
db_1  | vacuuming database template1 ... ok
db_1  | copying template1 to template0 ... ok
db_1  | copying template1 to postgres ... ok
db_1  | syncing data to disk ... ok
db_1  | 
db_1  | WARNING: enabling "trust" authentication for local connections
db_1  | You can change this by editing pg_hba.conf or using the option -A, or
db_1  | --auth-local and --auth-host, the next time you run initdb.
db_1  | 
db_1  | Success. You can now start the database server using:
db_1  | 
db_1  |     postgres -D /var/lib/postgresql/data
db_1  | or
db_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1  | 
db_1  | waiting for server to start....LOG:  database system was shut down at 2015-12-14 21:41:46 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
db_1  |  done
db_1  | server started
db_1  | ALTER ROLE
db_1  | 
db_1  | 
db_1  | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1  | 
db_1  | LOG:  received fast shutdown request
db_1  | LOG:  aborting any active transactions
db_1  | LOG:  autovacuum launcher shutting down
db_1  | LOG:  shutting down
db_1  | waiting for server to shut down....LOG:  database system is shut down
db_1  |  done
db_1  | server stopped
db_1  | 
db_1  | PostgreSQL init process complete; ready for start up.
db_1  | 
db_1  | LOG:  database system was shut down at 2015-12-14 21:41:47 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
db_1  | LOG:  received smart shutdown request
db_1  | LOG:  autovacuum launcher shutting down
db_1  | LOG:  shutting down
db_1  | LOG:  database system is shut down
db_1  | LOG:  database system was shut down at 2015-12-14 21:42:37 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
db_1  | LOG:  received smart shutdown request
db_1  | LOG:  autovacuum launcher shutting down
db_1  | LOG:  shutting down
db_1  | LOG:  database system is shut down
db_1  | LOG:  database system was shut down at 2015-12-14 21:49:55 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
web_1 | Traceback (most recent call last):
web_1 |   File "/usr/local/bin/kinto", line 9, in <module>
web_1 |     load_entry_point('kinto==1.11.0.dev0', 'console_scripts', 'kinto')()
web_1 |   File "/code/kinto/__main__.py", line 74, in main
web_1 |     pserve.main(pserve_argv)
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 60, in main
web_1 |     return command.run()
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 363, in run
web_1 |     relative_to=base, global_conf=vars)
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 405, in loadserver
web_1 |     server_spec, name=name, relative_to=relative_to, **kw)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 255, in loadserver
web_1 |     return loadobj(SERVER, uri, name=name, **kw)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
web_1 |     global_conf=global_conf)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
web_1 |     global_conf=global_conf)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
web_1 |     loader = ConfigLoader(path)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 393, in __init__
web_1 |     with open(filename) as f:
web_1 | FileNotFoundError: [Errno 2] No such file or directory: '/code/config/kinto.ini'
web_1 | Starting subprocess with file monitor
web_1 | Traceback (most recent call last):
web_1 |   File "/usr/local/bin/kinto", line 9, in <module>
web_1 |     load_entry_point('kinto==1.11.0.dev0', 'console_scripts', 'kinto')()
web_1 |   File "/code/kinto/__main__.py", line 74, in main
web_1 |     pserve.main(pserve_argv)
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 60, in main
web_1 |     return command.run()
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 363, in run
web_1 |     relative_to=base, global_conf=vars)
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 405, in loadserver
web_1 |     server_spec, name=name, relative_to=relative_to, **kw)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 255, in loadserver
web_1 |     return loadobj(SERVER, uri, name=name, **kw)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
web_1 |     global_conf=global_conf)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
web_1 |     global_conf=global_conf)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
web_1 |     loader = ConfigLoader(path)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 393, in __init__
web_1 |     with open(filename) as f:
web_1 | FileNotFoundError: [Errno 2] No such file or directory: '/code/config/kinto.ini'
web_1 | Starting subprocess with file monitor
web_1 | Traceback (most recent call last):
web_1 |   File "/usr/local/bin/kinto", line 9, in <module>
web_1 |     load_entry_point('kinto==1.11.0.dev0', 'console_scripts', 'kinto')()
web_1 |   File "/code/kinto/__main__.py", line 74, in main
web_1 |     pserve.main(pserve_argv)
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 60, in main
web_1 |     return command.run()
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 363, in run
web_1 |     relative_to=base, global_conf=vars)
web_1 |   File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 405, in loadserver
web_1 |     server_spec, name=name, relative_to=relative_to, **kw)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 255, in loadserver
web_1 |     return loadobj(SERVER, uri, name=name, **kw)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
web_1 |     global_conf=global_conf)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
web_1 |     global_conf=global_conf)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
web_1 |     loader = ConfigLoader(path)
web_1 |   File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 393, in __init__
web_1 |     with open(filename) as f:
web_1 | FileNotFoundError: [Errno 2] No such file or directory: '/code/config/kinto.ini'
web_1 | Starting subprocess with file monitor
kinto_web_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
Stopping kinto_db_1... done
```

**Comment by leplatrem** [comment]
Thanks @hansent for reporting this bug!

It looks like a consequence of #302, which was fixed and released recently.
Could you please try to pull the last version of the `kinto-server` container?

**Comment by saidimu** [comment]
The latest build of the Docker image (ID `b8ccaa29bb7f`) also fails with the same error:

`sudo docker run -p 8888:8888 kinto/kinto-server`

```
Traceback (most recent call last):
  File "/usr/local/bin/kinto", line 9, in <module>
    load_entry_point('kinto==1.11.0.dev0', 'console_scripts', 'kinto')()
  File "/code/kinto/__main__.py", line 74, in main
    pserve.main(pserve_argv)
  File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 325, in run
    relative_to=base, global_conf=vars)
  File "/usr/local/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 367, in loadserver
    server_spec, name=name, relative_to=relative_to, **kw)
  File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 255, in loadserver
    return loadobj(SERVER, uri, name=name, **kw)
  File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 317, in _loadconfig
    loader = ConfigLoader(path)
  File "/usr/local/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 393, in __init__
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/code/config/kinto.ini'
Starting subprocess with file monitor
```

**Comment by leplatrem** [comment]
Thanks for your feedback!

I could find the problem in the `Dockerfile` :)

**Comment by leplatrem** [comment]
Thanks @chartjes @hansent and @saidimu for bringing this up!

I just pulled and tested with the lastest container version and it is now fixed.

```
$ sudo docker pull kinto/kinto-server
Using default tag: latest
latest: Pulling from kinto/kinto-server
e7c6ac28919b: Pull complete 
1f32f6b0a215: Pull complete 
79efb74cdc69: Pull complete 
3a706ce797fa: Pull complete 
837c720db103: Pull complete 
5a9e9f07dab2: Pull complete 
Digest: sha256:cbd4264f9851c368664d0f542f54618f63404b7378f7a8165656e4845ff48ca6
Status: Downloaded newer image for kinto/kinto-server:latest
```
```
$ sudo docker run -p 8888:8888 kinto/kinto-server
2015-12-16 11:08:43,716 INFO  [venusian][MainThread] kinto 1.11.0.dev0 starting. 
...
```

**Comment by saidimu** [comment]
Thanks @leplatrem !
