### ISSUE TITLE
kinto init fails when the config folder already exists

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#337]
**Steps to reproduce**

First, create the default file. The parent folder `config/` will be created.
```
$ kinto --backend=memory init
```

If ran again, the command exits gracefully:
```
$ kinto --backend=memory init
config/kinto.ini already exist.
```

But if we delete the `kinto.ini` file and leave the `config/` folder, or if we specify another filename in the `config/` folder, then the commands fails:

```
$ kinto --backend=memory --ini=config/dev.ini init
Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto/.venv/bin/kinto", line 9, in <module>
    load_entry_point('kinto', 'console_scripts', 'kinto')()
  File "/home/mathieu/Code/Mozilla/kinto/kinto/__main__.py", line 66, in main
    init(config_file, backend)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/config/__init__.py", line 46, in init
    render_template("kinto.tpl", config_file, **values)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/config/__init__.py", line 12, in render_template
    os.makedirs(folder)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'config'
```

**Comment by Natim** [comment]
This was fixed by #349
