### ISSUE TITLE
kinto --version fails with an error

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#455]
I naively tried to retrieve the Kinto version from a venv, and got this:

```
$ ./.venv/bin/kinto --version 
Traceback (most recent call last):
  File "./.venv/bin/kinto", line 7, in <module>
    from kinto.__main__ import main
  File "/home/niko/work/kinto-client/.venv/local/lib/python2.7/site-packages/kinto/__main__.py", line 6, in <module>
    import pip
  File "/home/niko/work/kinto-client/.venv/local/lib/python2.7/site-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/niko/work/kinto-client/.venv/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/niko/work/kinto-client/.venv/local/lib/python2.7/site-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
```

**Comment by Natim** [comment]
Seems like a problem with the pip version installed in your virtualenv :(

**Comment by Natim** [comment]
However ``kinto --version`` doesn't exists:

```
$ ./.venv/bin/kinto --version
usage: kinto [-h] [--ini INI_FILE] [--backend BACKEND]
             {init,migrate,start} ...
kinto: error: too few arguments
```

**Comment by n1k0** [comment]
Right, we can probably close this issue if it doesn't to you, so it's related to my messed up env.

For the `--version` option to the `kinto` executable, I think it would be a worty addition. Should I file an new issue for this?

**Comment by n1k0** [comment]
Filed #457. Closing this one.
