### ISSUE TITLE
kinto 1.8 → 2.1: Data migration failed on last_modified column

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#559]
* Run kinto 1.8 
* Import some data
* Run kinto 2.0 after migrating the data

```
File \"\/data\/kinto-dist\/lib\/python2.7\/site-packages\/cornice\/service.py\", line 571, in wrapperdd
    response = view_()dd
  File \"\/data\/kinto-dist\/lib\/python2.7\/site-packages\/cliquet\/resource\/__init__.py\", line 404, in putdd
    unique_fields=unique)dd
  File \"\/data\/kinto-dist\/lib\/python2.7\/site-packages\/cliquet\/resource\/model.py\", line 294, in create_recorddd
    unique_fields)dd
  File \"\/data\/kinto-dist\/lib\/python2.7\/site-packages\/cliquet\/resource\/model.py\", line 177, in create_recorddd
    auth=self.auth)dd
  File \"\/data\/kinto-dist\/lib\/python2.7\/site-packages\/cliquet\/storage\/postgresql\/__init__.py\", line 237, in createdd
    inserted = result.fetchone()dd
  File \"\/usr\/lib64\/python2.7\/contextlib.py\", line 35, in __exit__dd
    self.gen.throw(type, value, traceback)dd
  File \"\/data\/kinto-dist\/lib\/python2.7\/site-packages\/cliquet\/storage\/postgresql\/client.py\", line 53, in connectdd
    raise exceptions.BackendError(original=e)dd
    BackendError: IntegrityError: (psycopg2.IntegrityError) null value in column \"last_modified\" violates not-null constraintdd
DETAIL:  Failing row contains (e6ca134f-8102-c9fa-acb2-b8df64727413, \/buckets\/blocklists\/collections\/certificates, record, null, {\"id\": \"e6ca134f-8102-c9fa-acb2-b8df64727413\", \"issuerName\": \"MF...).dd
 [SQL: '\dd
        WITH delete_potential_tombstone AS (\dd
            DELETE FROM deleted\dd
             WHERE id = %(object_id)s\dd
               AND parent_id = %(parent_id)s\dd
               AND collection_id = %(collection_id)s\dd
        )\dd
        INSERT INTO records (id, parent_id, collection_id, data, last_modified)\dd
        VALUES (%(object_id)s, %(parent_id)s,\dd
                %(collection_id)s, (%(data)s)::JSONB,\dd
                from_epoch(%(last_modified)s))\dd
        RETURNING id, as_epoch(last_modified) AS last_modified;\dd
        '] [parameters: {'collection_id': 'record', 'last_modified': None, 'data': '{\"issuerName\":\"MF8xCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRQwEgYDVQQLEwtQYXJ0bmVycyBDQTEfMB0GA1UEAxMWR2xvYmFsU2lnbiBQYXJ0bmVycyBDQQ==\",\"serialNumber\":\"BAAAAAABCfhiO+s=\",\"id\":\"e6ca134f-8102-c9fa-acb2-b8df64727413\"}', 'object_id': 'e6ca134f-8102-c9fa-acb2-b8df64727413', 'parent_id': u'\/buckets\/blocklists\/collections\/certificates'}]","uid":"98ed82c7b617baf0506a09f895c45bb44433f69b8879a712d21e75d7d2e7b17c","errno":110,"querystring":"{}","agent":"python-requests\/2.9.1","method":"PUT","collection_id":"record","path":"\/v1\/buckets\/blocklists\/collections\/certificates\/records\/e6ca134f-8102-c9fa-acb2-b8df64727413","authn_type":"basicauth","collection_timestamp":1461847208780},"Logger":"kinto","Type":["(psycopg2.IntegrityError) null value in column \"last_modified\" violates not-null constraintdd
        DETAIL:  Failing row contains (e6ca134f-8102-c9fa-acb2-b8df64727413, \/buckets\/blocklists\/collections\/certificates, record, null, {\"id\": \"e6ca134f-8102-c9fa-acb2-b8df64727413\", \"issuerName\": \"MF...).dd
"],"Severity":0}
```

**Comment by leplatrem** [comment]
@Natim @tarekziade @phrawzty  was it 1.8 ?

**Comment by Natim** [comment]
AFAIK, yes.

**Comment by leplatrem** [comment]
I could reproduce:

```
$ psql -h localhost -p 5432 -U postgres
```
```sql
CREATE DATABASE kinto18;
CREATE USER kinto18 WITH PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE kinto18 TO kinto18;
```

```
git clone git@github.com:Kinto/kinto.git
cd kinto
git co 1.8.0
```

```diff
diff --git a/config/kinto.ini b/config/kinto.ini
index a19006e..e4aa1ed 100644
--- a/config/kinto.ini
+++ b/config/kinto.ini
@@ -12,12 +12,12 @@ use = egg:kinto
 #
 # http://kinto.readthedocs.org/en/latest/configuration/settings.html#storage
 #
-# kinto.storage_backend = cliquet.storage.postgresql
-# kinto.storage_url = postgres://postgres:postgres@localhost/postgres
-# kinto.cache_backend = cliquet.cache.postgresql
-# kinto.cache_url = postgres://postgres:postgres@localhost/postgres
-# kinto.permission_backend = cliquet.permission.postgresql
-# kinto.permission_url = postgres://postgres:postgres@localhost/postgres
+kinto.storage_backend = cliquet.storage.postgresql
+kinto.storage_url = postgres://kinto18:postgres@localhost/kinto18
+kinto.cache_backend = cliquet.cache.postgresql
+kinto.cache_url = postgres://kinto18:postgres@localhost/kinto18
+kinto.permission_backend = cliquet.permission.postgresql
+kinto.permission_url = postgres://kinto18:postgres@localhost/kinto18
```

We didn't have the kinto command at the time:
```
$ virtualenv env
$ source env/bin/activate
$ pip install "cliquet[postgresql]"
$ python setup.py install
$ cliquet --ini config/kinto.ini migrate
$ pserve config/kinto.ini
```

Fill with some records:
```
git clone git@github.com:mozilla-services/xml2kinto.git
cd xml2kinto
git co onecrl-stable
KINTO_SERVER=http://localhost:8888 make sync -e
```

Upgrade kinto and migrate the database:
```
pip install -U "cliquet[postgresql]"
pip install -U kinto==2.0
kinto --ini config/kinto.ini migrate
pserve config/kinto.ini
```

And :bomb: : 

```
http PUT http://0.0.0.0:8888/v1/buckets/staging --auth user:pass
```

```
2016-04-28 23:57:58,123 DEBUG [cliquet.storage.postgresql.pool.QueuePoolWithMaxBacklog][waitress] Connection <connection object at 0x7fc55bb14050; dsn: 'dbname=kinto18 user=kinto18 password=xxxxxxxx host=localhost', closed: 0> checked out from pool
2016-04-28 23:57:58,129 ERROR [venusian][waitress] "PUT   /v1/buckets/staging" ? (? ms) (psycopg2.IntegrityError) null value in column "last_modified" violates not-null constraint
DETAIL:  Failing row contains (staging, , bucket, null, {"id": "staging"}).
 [SQL: '\n        WITH delete_potential_tombstone AS (\n            DELETE FROM deleted\n             WHERE id = %(object_id)s\n               AND parent_id = %(parent_id)s\n               AND collection_id = %(collection_id)s\n        )\n        INSERT INTO records (id, parent_id, collection_id, data, last_modified)\n        VALUES (%(object_id)s, %(parent_id)s,\n                %(collection_id)s, (%(data)s)::JSONB,\n                from_epoch(%(last_modified)s))\n        RETURNING id, as_epoch(last_modified) AS last_modified;\n        '] [parameters: {'collection_id': 'bucket', 'last_modified': None, 'data': '{"id":"staging"}', 'object_id': u'staging', 'parent_id': ''}] agent=HTTPie/0.9.2 authn_type=basicauth collection_id=bucket collection_timestamp=1461886924717 errno=110 lang=None uid=6de355038fd943a2dc91405063b91018bb5dd97a08d1beb95713d23c2909748f
2016-04-28 23:57:58,129 DEBUG [cliquet.storage.postgresql.pool.QueuePoolWithMaxBacklog][waitress] Connection <connection object at 0x7fc55bb14050; dsn: 'dbname=kinto18 user=kinto18 password=xxxxxxxx host=localhost', closed: 0> being returned to pool
2016-04-28 23:57:58,129 DEBUG [cliquet.storage.postgresql.pool.QueuePoolWithMaxBacklog][waitress] Connection <connection object at 0x7fc55bb14050; dsn: 'dbname=kinto18 user=kinto18 password=xxxxxxxx host=localhost', closed: 0> rollback-on-return, via agent
2016-04-28 23:57:58,130 CRITI [venusian][waitress] "PUT   /v1/buckets/staging" ? (? ms) (psycopg2.IntegrityError) null value in column "last_modified" violates not-null constraint
DETAIL:  Failing row contains (staging, , bucket, null, {"id": "staging"}).
 [SQL: '\n        WITH delete_potential_tombstone AS (\n            DELETE FROM deleted\n             WHERE id = %(object_id)s\n               AND parent_id = %(parent_id)s\n               AND collection_id = %(collection_id)s\n        )\n        INSERT INTO records (id, parent_id, collection_id, data, last_modified)\n        VALUES (%(object_id)s, %(parent_id)s,\n                %(collection_id)s, (%(data)s)::JSONB,\n                from_epoch(%(last_modified)s))\n        RETURNING id, as_epoch(last_modified) AS last_modified;\n        '] [parameters: {'collection_id': 'bucket', 'last_modified': None, 'data': '{"id":"staging"}', 'object_id': u'staging', 'parent_id': ''}] agent=HTTPie/0.9.2 authn_type=basicauth collection_id=bucket collection_timestamp=1461886924717 errno=110 exception=Traceback (most recent call last):
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 244, in _secured_view
    return view(context, request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/cornice/service.py", line 571, in wrapper
    response = view_()
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/cliquet/resource/__init__.py", line 404, in put
    unique_fields=unique)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/cliquet/resource/model.py", line 294, in create_record
    unique_fields)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/cliquet/resource/model.py", line 177, in create_record
    auth=self.auth)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/cliquet/storage/postgresql/__init__.py", line 237, in create
    inserted = result.fetchone()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mathieu/tmp/kinto/env/local/lib/python2.7/site-packages/cliquet/storage/postgresql/client.py", line 53, in connect
    raise exceptions.BackendError(original=e)
BackendError: IntegrityError: (psycopg2.IntegrityError) null value in column "last_modified" violates not-null constraint
DETAIL:  Failing row contains (staging, , bucket, null, {"id": "staging"}).
 [SQL: '
         WITH delete_potential_tombstone AS (
             DELETE FROM deleted
              WHERE id = %(object_id)s
                AND parent_id = %(parent_id)s
                AND collection_id = %(collection_id)s
         )
         INSERT INTO records (id, parent_id, collection_id, data, last_modified)
         VALUES (%(object_id)s, %(parent_id)s,
                 %(collection_id)s, (%(data)s)::JSONB,
                 from_epoch(%(last_modified)s))
         RETURNING id, as_epoch(last_modified) AS last_modified;
         '] [parameters: {'collection_id': 'bucket', 'last_modified': None, 'data': '{"id":"staging"}', 'object_id': u'staging', 'parent_id': ''}] lang=None uid=6de355038fd943a2dc91405063b91018bb5dd97a08d1beb95713d23c2909748f
```

**Comment by leplatrem** [comment]
Problem found: no triggers are defined, they must have been lost during migration. This means the [migrations test suite misses some expectations](https://github.com/mozilla-services/cliquet/blob/3.1.2/cliquet/tests/test_storage_migrations.py#L92-L137) !

Problem:
```sql
SELECT t.tgname FROM pg_trigger t, pg_proc p 
WHERE t.tgfoid=p.oid AND p.prosrc like '%record%';
 tgname 
--------
(0 rows)
```

Run the full SQL definition of the final schema using `psql` to fix the migrated one. It is idempotent and does not harm. 
```
$ psql -h localhost -p 5432 -U postgres
\c kinto18;
\i env/lib/python2.7/site-packages/cliquet/storage/postgresql/schema.sql
```

The triggers are back:
```
# select tgname from pg_trigger;
          tgname           
---------------------------
 tgr_records_last_modified
 tgr_deleted_last_modified
(2 rows)

Time: 0,303 ms
```

The creation now works \o/ 
```
http PUT http://0.0.0.0:8888/v1/buckets/staging --auth user:pass
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 158
Content-Type: application/json; charset=UTF-8
Date: Thu, 28 Apr 2016 22:06:39 GMT
Etag: "1461888399161"
Last-Modified: Fri, 29 Apr 2016 00:06:39 GMT
Server: waitress

{
    "data": {
        "id": "staging", 
        "last_modified": 1461888399161
    }, 
    "permissions": {
        "write": [
            "basicauth:6de355038fd943a2dc91405063b91018bb5dd97a08d1beb95713d23c2909748f"
        ]
    }
}
```

:smile:
