### ISSUE TITLE
PrintLogger' object has no attribute 'isEnabledFor'

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#628]
```
kinto start                                                          
event='Backend settings referring to cliquet are DEPRECATED. Please update your kinto.cache_backend setting to kinto.core.cache.memory (was: cliquet.cache.memory).'
event='Backend settings referring to cliquet are DEPRECATED. Please update your kinto.permission_backend setting to kinto.core.permission.memory (was: cliquet.permission.memory).'
event='Backend settings referring to cliquet are DEPRECATED. Please update your kinto.storage_backend setting to kinto.core.storage.memory (was: cliquet.storage.memory).'
Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto/.venv/bin/kinto", line 9, in <module>
    load_entry_point('kinto', 'console_scripts', 'kinto')()
  File "/home/mathieu/Code/Mozilla/kinto/kinto/__main__.py", line 97, in main
    pserve.main(pserve_argv)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 60, in main
    return command.run()
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 371, in run
    global_conf=vars)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 406, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/mathieu/Code/Mozilla/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/__init__.py", line 44, in main
    default_settings=DEFAULT_SETTINGS)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/core/initialization.py", line 553, in initialize
    config.include("kinto.core", route_prefix=api_version)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 800, in include
    c(configurator)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/core/__init__.py", line 176, in includeme
    logger.info(msg % settings)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/structlog/stdlib.py", line 67, in info
    return self._proxy_to_logger('info', event, *args, **kw)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    **event_kw)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/structlog/stdlib.py", line 327, in filter_by_level
    if logger.isEnabledFor(_NAME_TO_LEVEL[name]):
AttributeError: 'PrintLogger' object has no attribute 'isEnabledFor'
```

I could get rid of the error by removing the `logger.info()`  in `kinto/core/__init__.py`

**Comment by tarekziade** [comment]
I think that's related to the way the structlog factory is initalized to wrap python APIs

**Comment by glasserc** [comment]
Yes, @Natim and I saw this error a lot when I was adding the warnings/backwards compatibility to the settings stuff in #599. I thought I had put the logs in the right place (after the structlog init), but I guess not. I'll look at it.

**Comment by glasserc** [comment]
I'm a little stuck on this issue. We can't set up logging without loading settings, and we can't load settings without having set up logging (for when the settings are old and deprecated). I guess this works in the tests because we set up logging outside the test harness for these tests? I think the most sensible thing to do is to not call logging to print a deprecation warning. This means updating the tests to use some other mocked function, but that might be better anyhow.

**Comment by tarekziade** [comment]
One thing you can do is initialize the logger with default settings, and revisit them once the settings are loaded. It's a pattern I used in ather apps

**Comment by tarekziade** [comment]
I am -1 on avoiding to use logging before things get initialized, because you can't control what is going to happen. If a underlying lib calls a logging API you might get back the error.

It's quite simple to initialize the logging system - with a default  behavior that does like a print()

**Comment by glasserc** [comment]
I have reproduced the behavior using just structlog, so I believe this is partly a structlog bug, and I have opened https://github.com/hynek/structlog/issues/71 to track this issue.

**Comment by tarekziade** [comment]
Ok commenting there

**Comment by tarekziade** [comment]
proposed fix

```sh
$ git diff kinto/core/initialization.py
diff --git a/kinto/core/initialization.py b/kinto/core/initialization.py
index 26e5028..e08228f 100644
--- a/kinto/core/initialization.py
+++ b/kinto/core/initialization.py
@@ -318,7 +318,8 @@ def setup_logging(config):
     renderer_klass = config.maybe_dotted(settings['logging_renderer'])
     renderer = renderer_klass(settings)

-    structlog.configure(
+    structlog.wrap_logger(
+        logger,
         # Share the logger context by thread.
         context_class=structlog.threadlocal.wrap_dict(dict),
         # Integrate with Pyramid logging facilities.
```

**Comment by glasserc** [comment]
So, I've confirmed with upstream that there's a "bug" in structlog. I've issued https://github.com/hynek/structlog/pull/72 to try to fix it. We can wait until that gets merged and released, or we can merge one of the workarounds -- #632 or #633 are both equally ugly IMO.

**Comment by tarekziade** [comment]
if @hynek is willing to release your fix soon +1 for the proper fix.

**Comment by Natim** [comment]
https://github.com/hynek/structlog/pull/72 have been merged.

**Comment by leplatrem** [comment]
Fixed!
