### ISSUE TITLE
error with batch posting with default backend (maybe wrong use)

### ISSUE THREAD

**Issue by elelay** [Kinto/kinto#759]
I've written a nodejs program to batch insert ~4000 tickets in a collection.
I've batched them by 200 or less.
I force the id to the ticket id, but there are no duplicate ids.
Each batch is in a Promise, calling request. I've first combined the Promises with Promise.all, then serialized them, but get the same error.

Some posts fail with code 500, with following error on the docker run terminal.
Is this a known limitation of the default backend? An error in my code?

```
2016-08-16 14:57:02,332 ERROR [kinto.core.views.errors][waitress] "POST  /v1/buckets/e3e5dfdd-b5de-e9dd-e2ad-637fc2c6481f/collections/tickets/records" ? (? ms) dictionary changed size during iteration agent=None authn_type=basicauth collection_id=record collection_timestamp=1471359417323 errno=None exception=Traceback (most recent call last):
  File "/code/kinto/core/utils.py", line 322, in follow_subrequest
    return request.invoke_subrequest(subrequest, **kwargs), subrequest
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/code/kinto/plugins/default_bucket/__init__.py", line 159, in default_bucket
    response = request.invoke_subrequest(subrequest)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/usr/local/lib/python3.5/dist-packages/cornice/service.py", line 571, in wrapper
    response = view_()
  File "/code/kinto/core/resource/__init__.py", line 311, in collection_post
    existing = self._get_record_or_404(_id)
  File "/code/kinto/core/resource/__init__.py", line 681, in _get_record_or_404
    return self.model.get_record(record_id)
  File "/code/kinto/core/resource/model.py", line 276, in get_record
    permissions = self.permission.get_object_permissions(perm_object_id)
  File "/code/kinto/core/permission/__init__.py", line 136, in get_object_permissions
    perms = self.get_objects_permissions([object_id], permissions)
  File "/code/kinto/core/permission/memory.py", line 114, in get_objects_permissions
    aces = [k for k in self._store.keys()
  File "/code/kinto/core/permission/memory.py", line 114, in <listcomp>
    aces = [k for k in self._store.keys()
RuntimeError: dictionary changed size during iteration lang=None uid=84ffd9ad5044b2b77b40e0f96fee3112f02894fcbe0eec6dfb8008394955ab7f
2016-08-16 14:57:02,351 INFO  [kinto.core.views.batch][waitress] "POST  /v1/buckets/e3e5dfdd-b5de-e9dd-e2ad-637fc2c6481f/collections/tickets/records" 200 (22 ms) subrequest.summary agent=None authn_type=basicauth collection_id=record collection_timestamp=1471359422318 errno=None lang=None time=2016-08-16T14:57:02.351000 uid=84ffd9ad5044b2b77b40e0f96fee3112f02894fcbe0eec6dfb8008394955ab7f
2016-08-16 14:57:02,376 INFO  [kinto.core.views.batch][waitress] "POST  /v1/buckets/e3e5dfdd-b5de-e9dd-e2ad-637fc2c6481f/collections/tickets/records" 201 (33 ms) subrequest.summary agent=None authn_type=basicauth collection_id=record collection_timestamp=1471359422318 errno=110 lang=None time=2016-08-16T14:57:02.376000 uid=84ffd9ad5044b2b77b40e0f96fee3112f02894fcbe0eec6dfb8008394955ab7f
2016-08-16 14:57:02,381 INFO  [kinto.core.views.batch][waitress] "POST  /v1/buckets/e3e5dfdd-b5de-e9dd-e2ad-637fc2c6481f/collections/tickets/records" 200 (30 ms) subrequest.summary agent=None authn_type=basicauth collection_id=record collection_timestamp=1471359422318 errno=None lang=None time=2016-08-16T14:57:02.381000 uid=84ffd9ad5044b2b77b40e0f96fee3112f02894fcbe0eec6dfb8008394955ab7f
2016-08-16 14:57:02,381 ERROR [kinto.core.views.errors][waitress] "POST  /v1/buckets/e3e5dfdd-b5de-e9dd-e2ad-637fc2c6481f/collections/tickets/records" ? (? ms) dictionary changed size during iteration agent=None authn_type=basicauth collection_id=record collection_timestamp=1471359417323 errno=999 exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/usr/local/lib/python3.5/dist-packages/cornice/service.py", line 573, in wrapper
    response = view_(request)
  File "/code/kinto/core/views/batch.py", line 100, in post_batch
    use_tweens=False)
  File "/code/kinto/core/utils.py", line 326, in follow_subrequest
    raise e
  File "/code/kinto/core/utils.py", line 322, in follow_subrequest
    return request.invoke_subrequest(subrequest, **kwargs), subrequest
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/code/kinto/plugins/default_bucket/__init__.py", line 159, in default_bucket
    response = request.invoke_subrequest(subrequest)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/usr/local/lib/python3.5/dist-packages/cornice/service.py", line 571, in wrapper
    response = view_()
  File "/code/kinto/core/resource/__init__.py", line 311, in collection_post
    existing = self._get_record_or_404(_id)
  File "/code/kinto/core/resource/__init__.py", line 681, in _get_record_or_404
    return self.model.get_record(record_id)
  File "/code/kinto/core/resource/model.py", line 276, in get_record
    permissions = self.permission.get_object_permissions(perm_object_id)
  File "/code/kinto/core/permission/__init__.py", line 136, in get_object_permissions
    perms = self.get_objects_permissions([object_id], permissions)
  File "/code/kinto/core/permission/memory.py", line 114, in get_objects_permissions
    aces = [k for k in self._store.keys()
  File "/code/kinto/core/permission/memory.py", line 114, in <listcomp>
    aces = [k for k in self._store.keys()
RuntimeError: dictionary changed size during iteration lang=None uid=84ffd9ad5044b2b77b40e0f96fee3112f02894fcbe0eec6dfb8008394955ab7f
```

**Comment by elelay** [comment]
I've removed the custom id, to only use generated ids (I was getting errno=110 on occasions). Now I'm pretty sure I only get 201 or 500 responses.

**Comment by Natim** [comment]
Yes it looks like a race condition in the memory backend.
Do you mind testing with the PostgreSQL backend if you can reproduce the matter?

**Comment by elelay** [comment]
I'll try Tomorrow.

**Comment by elelay** [comment]
No error with the PostgreSQL backend.

**Comment by leplatrem** [comment]
`kinto start` relies on *waitress* which uses threads. We thus might have to introduce some mutex there...

**Comment by elelay** [comment]
This may be too much mutex!
I've switched to running from source:
 - default config, simply increased max_requests to 200
 - make serve

With master I get the exceptions listed in description but my program terminates.

With 759-fix-memory-mutual-exclusion I don't get the exceptions BUT my program doesn't terminate: cpu goes idle, but 3 out of 48 batch requests don't return. As soon as I interrupt kinto (Ctrl-C in its console) my program terminates (with socket errors from the returning requests).

There are no errors in the log file. Counting "201" lines, I get a total of 8438, while there are 8647 items to insert, so the program is stuck before it has inserted everything.

**Comment by elelay** [comment]
More data:
I've lowered the number of tickets to 400 (2 batches of 200 tickets) and it's still gets stuck for one of them.
I've got an hyperthreaded dual-core (appears as 4 cores in htop).
Once kinto is stuck and I interrupt my program, I can re-run it with more tickets and it all succeeds (as if the stuck kinto threads wouldn't get used anymore so wouldn't pose a problem on subsequent batch inserts).

**Comment by leplatrem** [comment]
@n1k0  made this script to load 10000 records : https://gist.github.com/n1k0/684c2b7e3150b101376b2bd429b7b19f
