### ISSUE TITLE
Crash in GET /permissions with 4.0

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#774]
```
(.venv)➜ http PUT :8888/v1/buckets/magic --auth user:pass
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 156
Content-Type: application/json; charset=UTF-8
Date: Thu, 18 Aug 2016 16:04:59 GMT
Etag: "1471536299925"
Last-Modified: Thu, 18 Aug 2016 16:04:59 GMT
Server: waitress

{
    "data": {
        "id": "magic", 
        "last_modified": 1471536299925
    }, 
    "permissions": {
        "write": [
            "basicauth:a9d81e1b56f2b77103e87601621a99b3d82a15abf7c72ce57a032d0964317c7a"
        ]
    }
}

```

```
(.venv)➜ http PUT :8888/v1/buckets/magic/collections/system --auth user:pass
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 157
Content-Type: application/json; charset=UTF-8
Date: Thu, 18 Aug 2016 16:05:07 GMT
Etag: "1471536307861"
Last-Modified: Thu, 18 Aug 2016 16:05:07 GMT
Server: waitress

{
    "data": {
        "id": "system", 
        "last_modified": 1471536307861
    }, 
    "permissions": {
        "write": [
            "basicauth:a9d81e1b56f2b77103e87601621a99b3d82a15abf7c72ce57a032d0964317c7a"
        ]
    }
}
```

```
(.venv)➜  http  :8888/v1/permissions --auth user:pass
HTTP/1.1 500 Internal Server Error
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 183
Content-Type: application/json; charset=UTF-8
Date: Thu, 18 Aug 2016 16:05:11 GMT
Server: waitress

{
    "code": 500, 
    "errno": 999, 
    "error": "Internal Server Error", 
    "info": "https://github.com/Kinto/kinto/issues/", 
    "message": "A programmatic error occured, developers have been informed."
}

```

```
ERROR  "GET   /v1/permissions" ? (? ms) 'NoneType' object has no attribute 'name' agent=node-fetch/1.0 (+https://github.com/bitinn/node-fetch) authn_type=basicauth errno=None exception=Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/mathieu/Code/Mozilla/kinto-client/.venv/local/lib/python2.7/site-packages/cornice/service.py", line 573, in wrapper
    response = view_(request)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/views/permissions.py", line 41, in permissions_get
    resource_name, matchdict = core_utils.view_lookup(request, object_uri)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/core/utils.py", line 390, in view_lookup
    resource_name = route.name.replace('-record', '')\
AttributeError: 'NoneType' object has no attribute 'name' lang=None uid=a9d81e1b56f2b77103e87601621a99b3d82a15abf7c72ce57a032d0964317c7a
```

**Comment by Natim** [comment]
I was not able to reproduce :s

**Comment by Natim** [comment]
```
$ http  :8888/v1/permissions --auth user:pass2016-08-18 18:19:34,887 INFO  [kinto.core.initialization][waitress] "GET   /v1/permissions" 200 (1 ms) request.summary agent=HTTPie/0.9.3 authn_type=basicauth errno=None lang=None time=2016-08-18T18:19:34 uid=c76f0598f9531be5f3dc43d8bf302163ded29474fbd778c4195e7315067db091
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 338
Content-Type: application/json; charset=UTF-8
Date: Thu, 18 Aug 2016 16:19:34 GMT
Server: waitress

{
    "data": [
        {
            "bucket_id": "magic", 
            "id": "magic", 
            "permissions": [
                "write", 
                "read", 
                "collection:create", 
                "group:create"
            ], 
            "resource_name": "bucket", 
            "uri": "/buckets/magic"
        }, 
        {
            "bucket_id": "magic", 
            "collection_id": "system", 
            "id": "system", 
            "permissions": [
                "write", 
                "read", 
                "record:create"
            ], 
            "resource_name": "collection", 
            "uri": "/buckets/magic/collections/system"
        }
    ]
}
```

**Comment by leplatrem** [comment]
It's reproduced on TravisCI : https://travis-ci.org/Kinto/kinto-http.js/jobs/153325171

![capture d ecran de 2016-08-18 18-28-53](https://cloud.githubusercontent.com/assets/546692/17781949/a57514f8-6571-11e6-93f9-985d30daebf0.png)

**Comment by leplatrem** [comment]
Its probably related to the history plugin, I'll have a look
