### ISSUE TITLE
TypeError: Note must be text (unicode)

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#924]
Latest master (393fbb3b189c7f1dc35eb266b738ef8056d4d4f5)

```
$ make serve
Serving on http://0.0.0.0:8888
2016-11-18 08:57:58,144 ERROR [kinto.core.views.errors][waitress] Note must be text (unicode) exception=Traceback (most recent call last):
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    reraise(*exc_info)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 85, in tm_tween
    t.note(native_(request.path_info, 'utf-8'))
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/transaction/_transaction.py", line 537, in note
    raise TypeError("Note must be text (unicode)")
TypeError: Note must be text (unicode)
2016-11-18 08:57:58,146 INFO  [kinto.core.initialization][waitress] request.summary errno=999 time=2016-11-18T08:57:58
2016-11-18 08:57:58,475 ERROR [kinto.core.views.errors][waitress] Note must be text (unicode) exception=Traceback (most recent call last):
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    reraise(*exc_info)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 85, in tm_tween
    t.note(native_(request.path_info, 'utf-8'))
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/transaction/_transaction.py", line 537, in note
    raise TypeError("Note must be text (unicode)")
TypeError: Note must be text (unicode)
```

**Comment by leplatrem** [comment]
See https://github.com/zopefoundation/transaction/blob/master/CHANGES.rst#201-2016-11-11

**Comment by leplatrem** [comment]
See issue upstream https://github.com/Pylons/pyramid_tm/issues/49

**Comment by leplatrem** [comment]
See Pylons/pyramid_tm#52

**Comment by leplatrem** [comment]
Fixed upstream
