### ISSUE TITLE
Change default listening address from 0.0.0.0 to 127.0.0.1 

### ISSUE THREAD

**Issue by julienrat** [Kinto/kinto#949]
Hi all !
I'm trying to run kinto in a local network without internet connexion, When i plug the internet on my kinto server, it works perfectly, but when i launch kinto with no internet connexion ! have got this errors : 

```
root@padaone:/home/padaone/formbuilder/kinto# make serve
.venv/bin/kinto --ini config/kinto.ini migrate
/home/padaone/formbuilder/kinto/kinto/core/initialization.py:568: UserWarning: HTTPS is not enabled
  warnings.warn('HTTPS is not enabled')
/home/padaone/formbuilder/kinto/kinto/core/storage/postgresql/client.py:88: UserWarning: Reuse existing PostgreSQL connection. Parameters permission_* will be ignored.
  warnings.warn(msg)
/home/padaone/formbuilder/kinto/kinto/core/storage/postgresql/client.py:88: UserWarning: Reuse existing PostgreSQL connection. Parameters cache_* will be ignored.
  warnings.warn(msg)
INFO   Running kinto 5.0.1.dev0. 
INFO   PostgreSQL cache schema is up-to-date. 
INFO   Detected PostgreSQL storage schema version 14. 
INFO   PostgreSQL storage schema is up-to-date. 
INFO   PostgreSQL permission schema is up-to-date. 
echo '{"name":"kinto","version":"5.0.0-19-g0cb4e9d","source":"https://github.com/Kinto/kinto.git","commit":"0cb4e9da6974a78f10d1a98ed0dd88f50a2417a3"}' > version.json
.venv/bin/kinto --ini config/kinto.ini start --reload
Starting subprocess with file monitor
/home/padaone/formbuilder/kinto/kinto/core/initialization.py:568: UserWarning: HTTPS is not enabled
  warnings.warn('HTTPS is not enabled')
/home/padaone/formbuilder/kinto/kinto/core/storage/postgresql/client.py:88: UserWarning: Reuse existing PostgreSQL connection. Parameters permission_* will be ignored.
  warnings.warn(msg)
/home/padaone/formbuilder/kinto/kinto/core/storage/postgresql/client.py:88: UserWarning: Reuse existing PostgreSQL connection. Parameters cache_* will be ignored.
  warnings.warn(msg)
2016-11-28 00:23:25,599 INFO  [kinto.core][MainThread] Running kinto 5.0.1.dev0. 
Starting server in PID 2685.
Traceback (most recent call last):
  File ".venv/bin/kinto", line 11, in <module>
    load_entry_point('kinto', 'console_scripts', 'kinto')()
  File "/home/padaone/formbuilder/kinto/kinto/__main__.py", line 149, in main
    pserve.main(pserve_argv)
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 60, in main
    return command.run()
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 403, in run
    serve()
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 382, in serve
    server(app)
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/waitress/__init__.py", line 20, in serve_paste
    serve(app, **kw)
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/waitress/server.py", line 85, in create_server
    sockinfo=sockinfo)
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/waitress/server.py", line 183, in __init__
    self.effective_host, self.effective_port = self.getsockname()
  File "/home/padaone/formbuilder/kinto/.venv/local/lib/python2.7/site-packages/waitress/server.py", line 299, in getsockname
    self.socketmod.NI_NUMERICSERV)
socket.gaierror: [Errno -3] Temporary failure in name resolution
```
What i'm doiing wrong ?
Thx again !

**Comment by Natim** [comment]
I've seen that in the past. Try to change the kinto.ini to use host = 127.0.0.1 rather than 0.0.0.0

**Comment by leplatrem** [comment]
Is there any good reason to keep `0.0.0.0` instead of `127.0.0.1` since it is rather unlikely that users will serve their kinto publicly with pserve?

**Comment by Natim** [comment]
Actually the Docker images do but yes I guess it is fine.

**Comment by PeriGK** [comment]
Hi there,

Looks like a simple change, the aforementioned IP is only located in a few places. Just checking though, do you mind if I just replace the IPs as is, or maybe "centralise" it a bit?

`grep -rn "0\.0\.0\.0" *
docs/troubleshooting.rst:134:port is already in use: ``listen tcp 0.0.0.0:5432: bind: address
docs/tutorials/authentication-github.rst:118:    serving on http://0.0.0.0:8888
kinto/config/kinto.tpl:7:host = 0.0.0.0
loadtests/server.ini:19:host = 0.0.0.0
tests/test_configuration/test.ini:7:host = 0.0.0.0
`

Cheers,
P.

**Comment by leplatrem** [comment]
Hi!

Awesome if you're willing to contribute the change!

There isn't much you can centralize I'm afraid :/ 

The docs reflect what the command output shows, and the configuration test will assert your change in the template.
The only exception is the loadtest where I think we can leave 0.0.0.0 since we may load test via a real network...

Thanks!

**Comment by PeriGK** [comment]
Cool, I can have a look :)
